<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="circuitoV3" nsURI="http://www.example.org/circuitoV3" nsPrefix="circuitoV3">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Sistema">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="vacioNombre nombre_repetido"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="vacioNombre" value="self.elementos->forAll(c1 | c1.nombreElemento&lt;>'' and c1.nombreElemento&lt;>null and c1->excludes(DataFlow))"/>
      <details key="nombre_repetido" value="self.elementos->forAll(c1,c2 | c1.nombreElemento=c2.nombreElemento implies c1=c2)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementos" upperBound="-1"
        eType="#//FlowElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pulsador" eSuperTypes="#//FlowSource">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="pin_fuera_rango"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="pin_fuera_rango" value="FlowSource.allInstances()->exists(numero_pin>1 and numero_pin&lt;13)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numero_pin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombreElemento" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estado" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowSource" abstract="true" eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="saliente_cambio" upperBound="-1"
        eType="#//DataFlow" containment="true" eOpposite="#//DataFlow/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowTarget" abstract="true" eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entrante_cambio" upperBound="-1"
        eType="#//DataFlow" eOpposite="#//DataFlow/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow" eSuperTypes="#//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//FlowTarget" eOpposite="#//FlowTarget/entrante_cambio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//FlowSource" eOpposite="#//FlowSource/saliente_cambio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Compuerta" abstract="true" eSuperTypes="#//FlowSource #//FlowTarget #//FlowElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pin_total" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Compuerta"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//Compuerta"/>
  <eClassifiers xsi:type="ecore:EClass" name="Not" eSuperTypes="#//Compuerta">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="variasConexiones"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="variasConexiones" value="Not.allInstances()->exists(self.entrante_cambio->size()&lt;2)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Led" eSuperTypes="#//FlowTarget">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="pin_fuera_rango varias_conexiones"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="pin_fuera_rango" value="FlowSource.allInstances()->exists(numero_pin>1 and numero_pin&lt;13)"/>
      <details key="varias_conexiones" value="Led.allInstances()->exists(self.entrante_cambio->size()&lt;2)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numero_pin" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
